### ISSUE TITLE
Crash: recyclerview invalid view holder adapter position

### ISSUE THREAD

**Issue by anuraag488** [itsdrnoob/DataMonitor#119]
----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 12
Version: v2.2.0
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 k2.a.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: Inconsistency detected. Invalid view holder adapter positiona{dfbaf2e position=8 id=-1, oldPos=-1, pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{22c35c4 VFE...... ........ 0,0-1080,1992 #7f09005c app:id/app_data_usage_recycler}, adapter:e2.d@8c5a977, layout:androidx.recyclerview.widget.LinearLayoutManager@ed599e4, context:com.drnoob.datamonitor.ui.activities.ContainerActivity@35a1ee6

----------Crash logs----------
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positiona{dfbaf2e position=8 id=-1,
 oldPos=-1,
 pLpos:-1 no parent} androidx.recyclerview.widget.RecyclerView{22c35c4 VFE...... ........ 0,
0-1080,
1992 #7f09005c app:id/app_data_usage_recycler},
 adapter:e2.d@8c5a977,
 layout:androidx.recyclerview.widget.LinearLayoutManager@ed599e4,
 context:com.drnoob.datamonitor.ui.activities.ContainerActivity@35a1ee6
	at androidx.recyclerview.widget.RecyclerView$t.i(SourceFile:578)
	at androidx.recyclerview.widget.m.c(SourceFile:46)
	at androidx.recyclerview.widget.m.b(SourceFile:187)
	at androidx.recyclerview.widget.m.run(SourceFile:78)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

----------Device info----------
Device Manufacturer: Xiaomi
Device Brand: Redmi
Device Model: Redmi Note 9 Pro Max
Device Codename: excalibur_in
Android version: 12, 31

**Comment by Satwik055** [comment]
How can i reproduce this error ?

**Comment by itsdrnoob** [comment]
> How can i reproduce this error ?

You probably can't. It happens rarely while refreshing the recycler view.
