### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by salad612** [itsdrnoob/DataMonitor#145]
Reoccurs after first launch every day it seems. Fairly sure it is due to me disabling network permission, custom ROM feature

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 11
Version: v2.2.0
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 k2.a.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: Unable to start receiver com.drnoob.datamonitor.utils.AppDataUsageMonitor$AppDataMonitor: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

----------Crash logs----------
java.lang.RuntimeException: Unable to start receiver com.drnoob.datamonitor.utils.AppDataUsageMonitor$AppDataMonitor: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4315)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2153)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.drnoob.datamonitor.utils.AppDataUsageMonitor$AppDataMonitor.onReceive(SourceFile:39)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4306)
	... 9 more

----------Device info----------
Android version: 13, 33

**Comment by itsdrnoob** [comment]
Fixed in 85ff049. By the way, was the device restarted prior to opening the app?

**Comment by salad612** [comment]
> Fixed in [85ff049](https://github.com/itsdrnoob/DataMonitor/commit/85ff049b0965f3d082be9b023298d12cde300d2f). By the way, was the device restarted prior to opening the app?

Yes.
