### ISSUE TITLE
Crash when changing Data Limit per month

### ISSUE THREAD

**Issue by mateo-meillon** [itsdrnoob/DataMonitor#154]
----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 13
Version: v2.2.0
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 k2.a.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: For input string: "10,00"

----------Crash logs----------
java.lang.NumberFormatException: For input string: "10,
00"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:455)
	at com.drnoob.datamonitor.ui.fragments.j0$f.onClick(SourceFile:45)
	at android.view.View.performClick(View.java:7763)
	at android.view.View.performClickInternal(View.java:7740)
	at android.view.View.access$3700(View.java:854)
	at android.view.View$PerformClick.run(View.java:29133)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8301)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)

----------Device info----------
Device Manufacturer: Xiaomi
Device Brand: Redmi
Device Model: 2201116SG
Device Codename: veux_eea
Android version: 12, 31

**Comment by itsdrnoob** [comment]
@Maettis Fixed in beta build. You can try it out and see if the issue persists.

**Comment by mateo-meillon** [comment]
Nice, thx
