### ISSUE TITLE
Data Monitor crashes after a while

### ISSUE THREAD

**Issue by GamerPowered97** [itsdrnoob/DataMonitor#159]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.3.0

### Steps to reproduce the bug

After a while that the app is open(usually around 1-2 hours) the data monitor notification pops up again and then right after the app crashes, it happens automatically even if my phone is not being used.
I also disabled every battery and app optimization settings 

### Logs

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 22
Version: v2.3.0
Thread name: Timer-29
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 p2.b.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: android.os.TransactionTooLargeException: data parcel size 2089248 bytes

----------Crash logs----------
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2089248 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:699)
	at android.app.NotificationManager.notify(NotificationManager.java:631)
	at b0.t.a(SourceFile:74)
	at com.drnoob.datamonitor.utils.CompoundNotification.a(SourceFile:1648)
	at com.drnoob.datamonitor.utils.CompoundNotification$b.run(SourceFile:21)
	at java.util.TimerThread.mainLoop(Timer.java:563)
	at java.util.TimerThread.run(Timer.java:513)
Caused by: android.os.TransactionTooLargeException: data parcel size 2089248 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:635)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:4231)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:696)
	... 6 more

----------Device info----------
Device Manufacturer: samsung
Device Brand: samsung
Device Model: SM-A125F
Device Codename: a12nseea
Android version: 12, 31

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy A12

**Comment by itsdrnoob** [comment]
@GamerPowered97 a fix will be pushed soon

**Comment by GamerPowered97** [comment]
Than you!

**Comment by GamerPowered97** [comment]
@itsdrnoob after the update the app works perfectly, and even a bit smoother.
Thanks for the fix
