### ISSUE TITLE
Crashed in Chinese Traditional 

### ISSUE THREAD

**Issue by bluehomewu** [itsdrnoob/DataMonitor#164]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.3.1(Beta) Download From PlayStore

### Steps to reproduce the bug

- Install beta version v2.3.1 from PlayStore.
- Open App, and setup language to Chinese Traditional.
- Apps will send you crashed message.

### Expected behavior

Without any crashed message.

### Actual behavior

Crashed.

### Screenshots/Screen recordings

![Screenshot_20230402-082619](https://user-images.githubusercontent.com/56945729/229324008-78aad3c8-c493-4874-96af-886ab037222d.png)

### Logs

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 23
Version: v2.3.1
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 p2.b.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: Attempt to read from null array

----------Crash logs----------
java.lang.NullPointerException: Attempt to read from null array
	at com.drnoob.datamonitor.ui.fragments.HomeFragment.g(SourceFile:371)
	at com.drnoob.datamonitor.ui.fragments.HomeFragment.onCreateView(Unknown Source:563)
	at androidx.fragment.app.Fragment.performCreateView(SourceFile:20)
	at androidx.fragment.app.f0.f(SourceFile:223)
	at androidx.fragment.app.f0.k(SourceFile:150)
	at androidx.fragment.app.z.O(SourceFile:62)
	at androidx.fragment.app.z.u(SourceFile:36)
	at androidx.fragment.app.Fragment.performViewCreated(Unknown Source:10)
	at androidx.fragment.app.f0.f(SourceFile:299)
	at androidx.fragment.app.f0.k(SourceFile:150)
	at androidx.fragment.app.z.O(SourceFile:62)
	at androidx.fragment.app.z.u(SourceFile:36)
	at androidx.fragment.app.o.onStart(SourceFile:34)
	at f.d.onStart(Unknown Source:0)
	at com.drnoob.datamonitor.ui.activities.MainActivity.onStart(SourceFile:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1564)
	at android.app.Activity.performStart(Activity.java:8315)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3698)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2305)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:227)
	at android.os.Looper.loop(Looper.java:327)
	at android.app.ActivityThread.main(ActivityThread.java:7951)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

----------Device info----------
Device Manufacturer: Nothing
Device Brand: Nothing
Device Model: A063
Device Codename: Spacewar
Android version: 13, 33

### Affected Android/Custom ROM version

Android 13 / Nothing OS 1.5.3

### Affected device model

Nothing Phone (1)

### Additional context

Only Crashed in Chinese Traditional.

**Comment by AlphonseHK** [comment]
Same here 😭

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 23
Version: v2.3.1
Thread name: AsyncTask #7
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 o2.b.uncaughtException(SourceFile:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: An error occurred while executing doInBackground()

----------Crash logs----------
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(Unknown Source:27)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	at com.drnoob.datamonitor.ui.activities.MainActivity$j.doInBackground(Unknown Source:943)
	at android.os.AsyncTask$3.call(Unknown Source:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more


----------Device info----------
Device Manufacturer: Xiaomi
Device Brand: Redmi
Device Model: 22081212G
Device Codename: diting
Android version: 13, 33

**Comment by bluehomewu** [comment]
I waited a long time, so I first compiled a version myself that fixed this issue.
v2.3.2
[Data Monitor_v2.3.2.apk.zip](https://github.com/itsdrnoob/DataMonitor/files/11262985/Data.Monitor_v2.3.2.apk.zip)

**Comment by itsdrnoob** [comment]
I did push a fix to the issue, as you can see here 8fd2577.
Couldn't push an update yet, as there as some more changes to be included and my exams are going on.
So I'd have to wait till it's over.

**Comment by bluehomewu** [comment]
> I did push a fix to the issue, as you can see here [8fd2577](https://github.com/itsdrnoob/DataMonitor/commit/8fd25775d8fb98f596dc1b82b66b95900d7864a5). Couldn't push an update yet, as there as some more changes to be included and my exams are going on. So I'd have to wait till it's over.

Nevermind, just make a quickly fixed build for someone who needs.
