### ISSUE TITLE
Crash: app no longer opens

### ISSUE THREAD

**Issue by snjy5** [itsdrnoob/DataMonitor#248]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.4.0

### Steps to reproduce the bug

1. Open the app 2. Crashes, open again. 3. Popup dialogue 'data monitor keeps crashing'

### Expected behavior

1. Open the app 2. Opens the app, app works properly and shows data usage

### Actual behavior

App crashes and upon multiple launch attempts it shows bug report/send feedback

### Logs

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 29
Version: v2.4.0
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1736),
 k4.b.uncaughtException(CrashReporter.java:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2203)]
Crash message: Unable to create service com.drnoob.datamonitor.utils.DataUsageMonitor: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a627, callingPackage: com.drnoob.datamonitor

----------Crash logs----------
java.lang.RuntimeException: Unable to create service com.drnoob.datamonitor.utils.DataUsageMonitor: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a627,
 callingPackage: com.drnoob.datamonitor
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4300)
	at android.app.ActivityThread.access$1600(ActivityThread.java:252)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1998)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7851)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a627,
 callingPackage: com.drnoob.datamonitor
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2382)
	at android.os.Parcel.createException(Parcel.java:2358)
	at android.os.Parcel.readException(Parcel.java:2341)
	at android.os.Parcel.readException(Parcel.java:2283)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:301)
	at android.app.AlarmManager.setImpl(AlarmManager.java:696)
	at android.app.AlarmManager.setExact(AlarmManager.java:541)
	at com.drnoob.datamonitor.utils.DataUsageMonitor.onCreate(DataUsageMonitor.java:105)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4288)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.AlarmManagerService.setImpl(AlarmManagerService.java:1779)
	at com.android.server.AlarmManagerService$4.set(AlarmManagerService.java:2136)
	at android.app.IAlarmManager$Stub.onTransact(IAlarmManager.java:168)
	at android.os.Binder.execTransactInternal(Binder.java:1168)
	at android.os.Binder.execTransact(Binder.java:1132)

----------Device info----------
Device Manufacturer: motorola
Device Brand: motorola
Device Model: moto g(9) play
Device Codename: guamp_retailn
Android version: 11, 30

### Affected Android/Custom ROM version

Android 11, Stock rom

### Affected device model

Moto g9 play

**Comment by snjy5** [comment]
`limit of concurrent alarms 500 reached for uid: u0a627`
I suspect it hit a process limit? I have been running the phone without rebooting for a while, few of other apps has also been misbehaving. Rebooting phone fix them, this app as well. Although rebooting phone shouldn't be the solution. Other system apps works fine, maybe they handle this error differently?

**Comment by itsdrnoob** [comment]
You're right. The error is a result of AlarmManager limit. Thanks for reporting it. Will look into it.
