### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by nascentphilosopher** [itsdrnoob/DataMonitor#252]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

V2.4.0 beta2

### Steps to reproduce the bug

Crash report 

### Expected behavior

Shouldn't crash

### Actual behavior

Crash report 

### Logs

----------Start of crash----------
Package: com.drnoob.datamonitor
Build type: release
Version code: 30
Version: v2.4.0
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 k4.b.uncaughtException(CrashReporter.java:91),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
Crash message: Bad notification for startForeground

----------Crash logs----------
android.app.RemoteServiceException: Bad notification for startForeground
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2017)
	at android.app.ActivityThread.access$2800(ActivityThread.java:261)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2249)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8098)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

----------Device info----------
Device Manufacturer: motorola
Device Brand: motorola
Device Model: moto g31
Device Codename: coful_g
Android version: 12, 31

**Comment by itsdrnoob** [comment]
Can you make sure if notification permissions are granted to the app?

**Comment by nascentphilosopher** [comment]
Yes
ΨΦ
