### ISSUE TITLE
Crash on "App data usage" view

### ISSUE THREAD

**Issue by shuvashish76** [itsdrnoob/DataMonitor#41]
**Describe the bug**

**To Reproduce**
1. Go to 'Network Diagnostics'
2. Click on 'Settings'
3. Back
4. Open 'App data usage'
5. App crashes

**Crash logs**

```
FATAL EXCEPTION: main
Process: com.drnoob.datamonitor, PID: 28446
java.lang.IllegalArgumentException: NetworkCallback was already unregistered
 at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
 at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3387)
 at com.drnoob.datamonitor.ui.fragments.NetworkDiagnosticsFragment$b.b(Unknown Source:4)
 at com.drnoob.datamonitor.ui.fragments.NetworkDiagnosticsFragment.onPause(:4)
 at androidx.fragment.app.Fragment.performPause(:2)
 at d.m.b.f0.l(Unknown Source:29)
 at d.m.b.f0.k(:6)
 at d.m.b.z.C(:11)
 at d.m.b.z.W(Unknown Source:91)
 at d.m.b.z.A(:4)
 at d.m.b.z$d.run(Unknown Source:3)
 at android.os.Handler.handleCallback(Handler.java:790)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6518)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Device details**
 - Device: Lenovo Tab4 8 plus
 - OS: Android 8.1.0
 - App version: **v2.0.0 (7)**

**Comment by itsdrnoob** [comment]
Couldn't reproduce. But i know what happened here.
Does it happen every time?
