### ISSUE TITLE
App data usage crash

### ISSUE THREAD

**Issue by shuvashish76** [itsdrnoob/DataMonitor#45]
**Describe the bug**

**To Reproduce**
1. Go to 'App data usage'
2. Click on any application
4. App crashes

**Crash logs**

```
FATAL EXCEPTION: AsyncTask #4
Process: com.drnoob.datamonitor, PID: 17167
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7334)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1165)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.requestLayout(View.java:21999)
	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(:2)
	at android.view.View.requestLayout(View.java:21999)
	at android.view.View.setFlags(View.java:13347)
	at android.view.View.setVisibility(View.java:9420)
	at e.c.a.a.d$b.doInBackground(:16)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

**Device details**
 - Device: Lenovo Tab4 8 plus
 - OS: android 8.1.0
 - App version: v2.0.0 (7)

**Additional context**
- It doesn't crash if I click App data usage > **Mobile Hotspot**
- It crashes everytime.

**Comment by itsdrnoob** [comment]
Couldn't reproduce, was it working on the previous version?

**Comment by itsdrnoob** [comment]
> All older versions (tested with v1.6.9 & v1.6.1) crashing before starting

You need to manually grant phone permission from settings in android 9 and below for the older versions.

**Comment by itsdrnoob** [comment]
@shuvashish76  Is this still a valid issue?

**Comment by shuvashish76** [comment]
> You need to manually grant phone permission from settings in android 9 and below for the older versions.

Thanks, I'll reopen if I face such issues in later versions. 👍🏿
